on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  types:
    runs-on: ubuntu-latest
    name: Generate types
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Codegen
        run: npm run codegen
        env:
          CONTENTFUL_SPACE: ${{secrets.CONTENTFUL_SPACE}}
          CONTENTFUL_ENVIRONMENT: ${{secrets.CONTENTFUL_ENVIRONMENT}}
          CONTENTFUL_DELIVERY_ACCESS_TOKEN: ${{secrets.CONTENTFUL_DELIVERY_ACCESS_TOKEN}}

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, types, build]
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Codegen
        run: npm run codegen
        env:
          CONTENTFUL_SPACE: ${{secrets.CONTENTFUL_SPACE}}
          CONTENTFUL_ENVIRONMENT: ${{secrets.CONTENTFUL_ENVIRONMENT}}
          CONTENTFUL_DELIVERY_ACCESS_TOKEN: ${{secrets.CONTENTFUL_DELIVERY_ACCESS_TOKEN}}
      - name: Build
        run: npm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'remix-contentful-example'
          directory: 'public'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
